### ISSUE TITLE
Color LCD Incorrect Button Event

### ISSUE THREAD

**Issue by Godofdrakes** [sidewinder94/Logitech-LCD#4] opened 2015-08-10 00:34 UTC
Every button on my g19s is triggering the LcdColorLeftButtonPressed event, including the back and menu buttons which I have not bound.

Bindings:
```XAML
    <applets:BaseWPFApplet x:Name="lcdScreen"
                           LcdColorUpButtonPressed="lcdScreen_LcdColorUpButtonPressed"
                           LcdColorDownButtonPressed="lcdScreen_LcdColorDownButtonPressed"
                           LcdColorLeftButtonPressed="lcdScreen_LcdColorLeftButtonPressed"
                           LcdColorRightButtonPressed="lcdScreen_LcdColorRightButtonPressed"
                           LcdColorOkButtonPressed="lcdScreen_LcdColorOkButtonPressed">
```
Code:
```C#
private void lcdScreen_LcdColorUpButtonPressed( object sender, EventArgs e ) {
    ++Number.Y;
}
private void lcdScreen_LcdColorDownButtonPressed( object sender, EventArgs e ) {
    --Number.Y;
}
private void lcdScreen_LcdColorLeftButtonPressed( object sender, EventArgs e ) {
    --Number.X;
}
private void lcdScreen_LcdColorRightButtonPressed( object sender, EventArgs e ) {
    ++Number.X;
}
private void lcdScreen_LcdColorOkButtonPressed( object sender, EventArgs e ) {
    Number.X = 0;
    Number.Y = 0;
 }
```

Removing the binding for the left button stops all buttons from triggering any events.

My g19s is working correctly as I can press the App selection key to switch away form my App to others that work fine.

As a possibly related note:

I initially had some trouble getting the DLL included. Init was complaining it couldn't find LogitechLCD.dll.  I couldn't tell if it wanted the Logitech-LCD.dll file built in your project, the LogitechLcdEnginesWrapper.dll (the only DLL in my download of the [Gamepanel SDK](gaming.logitech.com/en-us/developers)) or some DLL I had to build myself from the SDK's header and lib files.

Through trial and error I found it to be the EnginesWrapper and applied a band-aid to the problem by editing NativeMethods.cs (DllName86/DllName64) to reflect this and using a post build event to copy the entire Lib folder to the directory of the built exe. Not sure if that's necessary the best fix but it can Init and is rendering properly now.

**Comment by sidewinder94** [comment] 2015-08-10 08:37
You got it right for the dll name.

They changed the name in the recent releases of the SDK, but it IS the wrapper DLL, I'll update the readme accordingly.

I'll check why the left button is triggering all of the event.

**Comment by sidewinder94** [comment] 2015-08-10 08:55
@Godofdrakes : Mind getting the latest version and trying again ? 

Seeing what the error was i'm amazed the other buttons even worked.

**Comment by sidewinder94** [comment] 2015-08-10 09:20
Tested on a minimal project, all seems to work correctly.

Waiting for your feedback before closing

**Comment by Godofdrakes** [comment] 2015-08-11 00:38
Fixed!

Also minor question. I have to disable the signing of the assembly to build the dll as the key file is missing. That normal?

**Comment by sidewinder94** [comment] 2015-08-11 12:03
Yup, this is because I'm signing by default, you can either use your own key or disable it.

I'll try to see if I can disable the signing for debug versions

Closing, since the issue is resolved

**Closed by sidewinder94** 2015-08-11 12:03 UTC
Labels: bug
